### ISSUE TITLE
Why is it slow??

### ISSUE THREAD

**Issue by mopilo** [kelset/react-native-glshaders-testing#4]
Please can you say while it is slow??

**Comment by kelset** [comment]
Oh hi there - well, as the name of the repo says, this was a test repo. I was just messing around to see how to manage to obtain the instagram like effect.

And I also wrote in the readme that it is, in fact, [slow](https://github.com/kelset/react-native-glshaders-testing#current-issues).

Regarding the reasons why, probably because the way I implemented it was still quite JS-heavy. And gl-react-native was not as optimized as it could be (I think).

If you need to do something like this, I suggest you read [this article](https://blog.expo.io/filtering-images-with-expo-ffd8f053bc85) by Evan Bacon.

**Comment by mopilo** [comment]
Yeah I saw the part in the readme file saying its slow,  I just wanted to know why. 
Thanks for answering  the question

**Comment by mopilo** [comment]
Well I using native code for my react native app,  and the article you sent probably  won't help,  any suggestions on how to make it faster on native code??
